// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy-ssK0k6JEWksDt4w2RK9ti1_oYTe1zg',
    appId: '1:1092155565727:web:1fbc8d6f02fd6b9dece4aa',
    messagingSenderId: '1092155565727',
    projectId: 'chatzy-8d0b9',
    authDomain: 'chatzy-8d0b9.firebaseapp.com',
    storageBucket: 'chatzy-8d0b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbwp8j5VjNnvgqSmPRjxko6Y7XQPnzHgw',
    appId: '1:1092155565727:android:c7cf09a6da860a25ece4aa',
    messagingSenderId: '1092155565727',
    projectId: 'chatzy-8d0b9',
    storageBucket: 'chatzy-8d0b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA6inyagonzXYp1a-pSf674bcbnKVdp30',
    appId: '1:1092155565727:ios:fe16467d1fd91152ece4aa',
    messagingSenderId: '1092155565727',
    projectId: 'chatzy-8d0b9',
    storageBucket: 'chatzy-8d0b9.appspot.com',
    iosBundleId: 'com.example.chatzy',
  );
}
